from __future__ import annotations

from physicsos.schemas.common import ArtifactRef
from physicsos.schemas.surrogate import SurrogateModelSpec


SURROGATE_MODELS: tuple[SurrogateModelSpec, ...] = (
    SurrogateModelSpec(
        id="grid_fno_v0",
        name="Grid FNO scaffold",
        family="grid_neural_operator",
        domains=["fluid", "thermal", "solid", "custom"],
        operator_families=["navier_stokes", "heat", "poisson", "elasticity"],
        geometry_encodings=["multi_resolution_grid", "occupancy_mask"],
        mesh_kinds=["structured"],
        steady=None,
        supports_transient=True,
        runner="scaffold",
        expected_fields=["geometry", "parameters", "boundary_conditions"],
        output_fields=["field"],
        notes=["Use for regular-grid or voxelized PDE benchmarks."],
    ),
    SurrogateModelSpec(
        id="geometry_informed_no_v0",
        name="Geometry-informed neural operator scaffold",
        family="geometry_informed_neural_operator",
        domains=["fluid", "thermal"],
        operator_families=["navier_stokes", "heat", "conjugate_heat_transfer"],
        geometry_encodings=["sdf", "occupancy_mask", "surface_point_cloud", "multi_resolution_grid"],
        mesh_kinds=["structured", "unstructured", "hybrid", "none"],
        steady=None,
        supports_transient=True,
        runner="scaffold",
        expected_fields=["sdf", "boundary_conditions", "dimensionless_numbers"],
        output_fields=["U", "p", "T"],
        notes=["Primary target for complex geometry CFD/thermal surrogate MVP."],
    ),
    SurrogateModelSpec(
        id="mesh_graph_operator_v0",
        name="Mesh graph operator scaffold",
        family="mesh_graph_operator",
        domains=["fluid", "thermal", "solid", "electromagnetic", "multiphysics"],
        operator_families=["navier_stokes", "heat", "elasticity", "maxwell", "poisson"],
        geometry_encodings=["mesh_graph", "boundary_graph"],
        mesh_kinds=["unstructured", "hybrid", "surface", "volume"],
        steady=None,
        supports_transient=True,
        runner="scaffold",
        expected_fields=["mesh_graph", "node_features", "edge_features", "boundary_features"],
        output_fields=["field"],
        notes=["Use for arbitrary meshes and mesh-conditioned generalization."],
    ),
    SurrogateModelSpec(
        id="manifold_operator_v0",
        name="Manifold operator scaffold",
        family="manifold_operator",
        domains=["solid", "electromagnetic", "custom"],
        operator_families=["surface_pde", "shell", "membrane", "laplace_beltrami"],
        geometry_encodings=["surface_point_cloud", "laplacian_eigenbasis", "mesh_graph"],
        mesh_kinds=["surface"],
        steady=None,
        supports_transient=True,
        runner="scaffold",
        expected_fields=["surface_geometry", "boundary_features"],
        output_fields=["surface_field"],
        notes=["Use for PDEs on surfaces/manifolds."],
    ),
    SurrogateModelSpec(
        id="pinn_corrector_v0",
        name="PINN residual corrector scaffold",
        family="pinn_corrector",
        domains=["fluid", "thermal", "solid", "custom"],
        operator_families=["any_residual_defined_operator"],
        geometry_encodings=["sdf", "surface_point_cloud", "volume_point_cloud"],
        mesh_kinds=["structured", "unstructured", "hybrid", "none"],
        steady=None,
        supports_transient=True,
        runner="scaffold",
        expected_fields=["coordinates", "operator_residual"],
        output_fields=["correction"],
        notes=["Use as residual-based corrector, not default fast solver."],
    ),
    SurrogateModelSpec(
        id="taps_v0",
        name="TAPS a priori surrogate scaffold",
        family="taps",
        domains=["fluid", "thermal", "solid", "custom"],
        operator_families=["parameterized_pde", "space_parameter_time_galerkin"],
        geometry_encodings=["parametric_shape_vector", "laplacian_eigenbasis"],
        mesh_kinds=["structured", "unstructured", "none"],
        steady=None,
        supports_transient=True,
        checkpoint=ArtifactRef(uri="/models/taps_v0", kind="model_checkpoint", format="directory"),
        runner="scaffold",
        expected_fields=["operator", "parameter_axes", "basis"],
        output_fields=["reduced_solution"],
        notes=["Equation-driven a priori surrogate for large parameter/time spaces."],
    ),
)
